### ISSUE TITLE
Add support for foreign language BaK versions

### ISSUE THREAD

**Issue by xavieran** [xavieran/BaKGL#208]

**Comment by xavieran** [comment]
Check version does not work out of the box:
```
11:05:30.11 DEBUG [SpriteManager] Adding sprite sheet index: 11
11:05:30.11 FATAL [BAK::Font] Request for bad char: {8} ] FirstChar is: 32
main3d: /home/xavieran/Code/BaKGL/./bak/font.hpp:56: char BAK::Font::GetIndex(char) const: Assertion `(mFirstChar <= c)' failed.
```
And
```
SPAM [DialogStore] Offset { 0 @ 0x17d97 } @ [ ds: 0 act: 0 ds2: 0 ds3: 0 ]
Text [  ]
Next [ None ]

Requested: 2 but @97703 mSize: 97704 @: 0x7ffff5cb4f66 to  @: 0x7ffff5cb4f65
FATAL [FileBuffer] /home/xavieran/Code/BaKGL/bak/file/fileBuffer.cpp:929 GetData BufferEmpty!
terminate called after throwing an instance of 'std::runtime_error'
  what():  /home/xavieran/Code/BaKGL/bak/file/fileBuffer.cpp:929 GetData BufferEmpty!

Program received signal SIGABRT, Aborted.
0x00007ffff750c3f4 in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff750c3f4 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff74b3120 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff749a4c3 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7ca0b2c in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff7cb6f3a in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff7ca052a in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff7cb71f6 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x5555555eaba0 <typeinfo for std::runtime_error@GLIBCXX_3.4>, 
    dest=0x7ffff7cce7a0 <std::runtime_error::~runtime_error()>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00005555555ab4dc in BAK::FileBuffer::GetData (this=0x7fffffffd110, data=0x7fffffffcf36, n=2) at /home/xavieran/Code/BaKGL/bak/file/fileBuffer.cpp:931
#8  0x00005555555aa7a1 in BAK::FileBuffer::GetUint16LE (this=0x7fffffffd110) at /home/xavieran/Code/BaKGL/bak/file/fileBuffer.cpp:803
#9  0x000055555556526c in BAK::DialogSnippet::DialogSnippet (this=0x7fffffffd150, fb=..., dialogFile=0 '\000') at /home/xavieran/Code/BaKGL/bak/dialog.cpp:81
#10 0x0000555555566a4a in BAK::DialogStore::Load (this=0x5555555eb720 <BAK::DialogStore::Get()::dialogStore>) at /home/xavieran/Code/BaKGL/bak/dialog.cpp:426
#11 0x00005555555666f0 in BAK::DialogStore::DialogStore (this=0x5555555eb720 <BAK::DialogStore::Get()::dialogStore>) at /home/xavieran/Code/BaKGL/bak/dialog.cpp:398
#12 0x00005555555665d4 in BAK::DialogStore::Get () at /home/xavieran/Code/BaKGL/bak/dialog.cpp:388
#13 0x000055555555a992 in main (argc=1, argv=0x7fffffffd7a8) at /home/xavieran/Code/BaKGL/app/display_dialog.cpp:24
(gdb) q

```

**Comment by Tormentor667** [comment]
Well, the issue seems to be the german special glyphs called "Umlaute" (ö,ä,ü and for sure the sharp s - ß). Maybe you somehow need to tell the right unicode or whatever it is. The german game version actually has the proper glyphs.
